// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for ios - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDxAq4vtGk0h5vchyAV9K5ZT4mFDsWxyJ4',
//     appId: '1:1009392593124:web:06600f30e0b8c022e5e4f1',
//     messagingSenderId: '1009392593124',
//     projectId: 'random-5ce5b',
//     authDomain: 'random-5ce5b.firebaseapp.com',
//     storageBucket: 'random-5ce5b.appspot.com',
//     measurementId: 'G-3B11LHLZ1X',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDjU3VoXSvnuhphD5-RZUvRQiGfVWu7Q8M',
//     appId: '1:1009392593124:android:91378ffba2856dd2e5e4f1',
//     messagingSenderId: '1009392593124',
//     projectId: 'random-5ce5b',
//     storageBucket: 'random-5ce5b.appspot.com',
//   );
// }

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxAq4vtGk0h5vchyAV9K5ZT4mFDsWxyJ4',
    appId: '1:1009392593124:web:06600f30e0b8c022e5e4f1',
    messagingSenderId: '1009392593124',
    projectId: 'random-5ce5b',
    authDomain: 'random-5ce5b.firebaseapp.com',
    storageBucket: 'random-5ce5b.appspot.com',
    measurementId: 'G-3B11LHLZ1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjU3VoXSvnuhphD5-RZUvRQiGfVWu7Q8M',
    appId: '1:1009392593124:android:91378ffba2856dd2e5e4f1',
    messagingSenderId: '1009392593124',
    projectId: 'random-5ce5b',
    storageBucket: 'random-5ce5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFwZ__example-key',
    appId: '1:1009392593124:ios:exampleappId',
    messagingSenderId: '1009392593124',
    projectId: 'random-5ce5b',
    storageBucket: 'random-5ce5b.appspot.com',
    iosClientId: 'example-client-id',
    iosBundleId: 'com.example.app',
  );
}
